version: '3.1'

services:
  nestjs_pg:
    image: postgres:16.0
    container_name: nestjs_pg
    restart: always
    environment:
      POSTGRES_DB: nestjsdb
      POSTGRES_USER: manuelfbs
      POSTGRES_PASSWORD: secret1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432